defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/node:8

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          key: yarn-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies 
          command: yarn install
      - save_cache:
          key: yarn-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules


  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Deploy to heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/whatsapp-react.git master

workflows:
  version: 2

  build_and_deploy:
    jobs:
    - build
    - deploy:
        requires:
          - build
