defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/node:8

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules


  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Deploy to heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/whatsapp-react.git master

workflows:
  version: 2

  build_and_deploy:
    jobs:
    - build
    - deploy:
        requires:
          - build